Huggingface Integrations
alex-petrenko/sample-factory pull request #175
Opened 2022-07-20 22:46 UTC by andrewzhang505

Added code to generate videos and push to huggingface hub to enjoy.py and added documentation

2022-07-21 01:37 UTC, alex-petrenko requested changes
I requested some minor changes.
This is a great feature!

2022-07-21 01:37 UTC, alex-petrenko commented on sample_factory/enjoy.py
> +                        if cfg.save_video:
Can you move this to a separate function so that we don't repeat the same code twice?

Also I think we can remove @wmFrank 's comment about atari

2022-07-21 01:37 UTC, alex-petrenko commented on sample_factory/enjoy.py
> +    if cfg.push_to_hub:
This is very cool. I didn't know you automated this!

2022-07-21 01:37 UTC, alex-petrenko commented on sample_factory/utils/huggingface_utils.py
> +    tmp_name = "/tmp/replay.mp4"
Just in case, maybe use `project_tmp_dir` for this. I faced some issues with /tmp on clusters.
Just to be safe.

2022-07-21 01:37 UTC, alex-petrenko commented on docs/get-started/huggingface.md
> +1. Download `git lfs` with `sudo apt install git-lfs`
@andrewzhang505 can you explain this part? What does git lfs have to do with anything? I'm curious

Also instruction step 3. says just `git clone ` without an actual path. Is this intended?

2022-07-21 02:01 UTC, alex-petrenko commented on docs/get-started/huggingface.md
> +1. Download `git lfs` with `sudo apt install git-lfs`
Maybe where you first mention a repo, say "HuggingFace Hub repo".
I thought for a second that it has something to do with our repo.
<link to your huggingface repo> should be good too

2022-07-21 16:53 UTC, simoninithomas reviewed
Excellent work! The integration is super clean 👌 .

**I think we can add a load_from_hf directly instead of git clone the repo ?** We done that with Stable Baselines3 and ML-Agents I link the integrations here:
1. https://github.com/huggingface/huggingface_sb3/blob/main/huggingface_sb3/load_from_hub.py
2. https://github.com/huggingface/ml-agents/blob/main/ml-agents/mlagents/utils/load_from_hf.py

I was just wondering **for the name of the functions, in** MLAgents and Stable Baselines 3 integrations we used:
- load_from_hf: to load a model
- push_to_hf and package_to_hub (package_to_hub is a more complex function to evaluate the model, generate a video and a model card with Stable Baselines3 and RL-Zoo). 
 
We can use push_to_hub or push_to_hf or push_model_to_hf or push_model_to_hub?

2022-07-25 06:23 UTC, alex-petrenko approved these changes

2022-07-25 06:23 UTC, alex-petrenko commented on docs/get-started/huggingface.md
> +You can upload your models to the Hub using your environment's `enjoy` script with the `--push_to_hub` flag. Uploading using `enjoy` can also generate evaluation metics and a replay video.
*metrics

2022-07-25 06:23 UTC, merged