Add obstacles
alex-petrenko/sample-factory pull request #69
Opened 2020-11-05 09:06 UTC by Zhehui-Huang

2020-11-06 06:34 UTC, alex-petrenko requested changes

2020-11-06 06:34 UTC, alex-petrenko commented on envs/quadrotors/quadrotor_params.py
> +    p.add_argument('--quads_obstacle_mode', default='None', type=str, choices=['None', 'static', 'dynamic'], help='Choose which obstacle mode to run')
Can we change this from `None` to `no_obstacles` to avoid confusion with Python's None?
Just in case

2020-11-06 06:34 UTC, alex-petrenko commented on envs/quadrotors/quad_multi_model.py
> +            self.feed_forward = fc_layer(self.self_encoder_out_size + self.neighbor_encoder_out_size + self.obstacle_encoder_out_size, cfg.hidden_size, spec_norm=self.use_spectral_norm)
Lots of code duplication here.
Just calculate the total encoder output size as you go and use it to create fc_layer. Please try to minimize code duplication as much as you can

2020-11-06 06:34 UTC, alex-petrenko commented
Great work! Minor changes requested.

2020-11-06 16:25 UTC, Zhehui-Huang commented
I have made some modifications given by your suggestions, please check.

2020-11-07 00:22 UTC, alex-petrenko approved these changes

2020-11-07 00:24 UTC, merged